sudo: required
services:
  - docker

before_install:
  - docker build -t ankurrathore/docker-react -f DockerFile.Dev .

script:
  - docker run -e CI=true ankurrathore/docker-react npm run test -- --coverage
